from __future__ import annotations

PACKAGE_VERSION = "1"
STATE_SCHEMA_VERSION = 1
DB_SCHEMA_VERSION = 1

EMBED_MODEL = "text-embedding-3-small"
EMBED_DIM = 256
EMBED_BATCH_SIZE = 48
EMBED_MAX_CHARS = 6000
EMBED_ENDPOINT = "https://api.openai.com/v1/embeddings"

RERANK_MODEL = "gpt-4.1-mini"
RERANK_ENDPOINT = "https://api.openai.com/v1/responses"
RERANK_POOL = 50
RERANK_CHAR_BUDGET = 700

SQLITE_VEC_REQUIREMENT = "sqlite-vec==0.1.9"
SQLITE_VEC_VERSION = "0.1.9"

DEFAULT_PATTERN = "**/*.md"
DEFAULT_TOP_K = 15
DEFAULT_CANDIDATE_POOL = 120
DEFAULT_RRF_K = 60

MIN_CHUNK_CHARS = 200
MAX_CHUNK_CHARS = 4000
CHUNK_OVERLAP_CHARS = 250

SECURE_FETCH_SECRET_KEY = "OPENAI_API_KEY"
SECURE_FETCH_TIMEOUT_MS = 60_000
SECURE_FETCH_MAX_RESPONSE_BYTES = 10_000_000
